require "open-uri"
require "nokogiri"
require "pry"
require_relative "nyt_best_sellers_cli_app/version"
require_relative "./nyt_best_sellers_cli_app/cli"
require_relative "./nyt_best_sellers_cli_app/book"
